config/routes.rb
WeeklyMonthly::Application.routes.draw do
  resources :chores
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy ]

get "/calendars" => "calendars#index"

get 'login'  => 'user_sessions#new'
get 'logout' => 'user_sessions#destroy'

  root 'user_sessions#new'

  

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  attr_accessor :day, :month
  def initialize
    @day = Date.today.day
    @month = Date.today.month
  end

  def begin_weekly_calendar
    @begin_calendar = Date.today.beginning_of_week(start_day = :sunday)
  end

  def end_weekly_calendar(weeks)
    @begin_calendar = Date.today.beginning_of_week(start_day = :sunday)
    @end_calendar = @begin_calendar + (weeks*7)-1
  end
end

app/models/chore.rb
class Chore < ActiveRecord::Base
  validates :title, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @calendar = Calendar.new
  end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, only: [:show, :edit, :update, :destroy]
  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chore }
      else
        format.html { render action: 'new' }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:title, :body, :day, :tag, :date_due, :schedule)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:username], params[:password])
      redirect_back_or_to(users_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:users, message: 'Logged out!')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :zero_users_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]
  # GET /users
  # GET /users.json

  def zero_users_or_authenticated
    unless User.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/_calendar.html.erb
<table id="cal">
  <tr>
    <th>Sunday</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Saturday</th>
  </tr>
  <tr>
    <% (begin_weekly_calendar..end_weekly_calendar(2)).each do |d| %>
      <% if d.wday == 0 %></tr><tr><% end %>
        <td>
          <%= d.day %>
          <ul>
            <% @chore.todays_events(d.to_date).each do |e| %>
              <li><%= e.title %></li>
            <% end %>
          </ul>
        </td>
      <% end %>
  </tr>
</table>

app/views/calendars/index.html.erb
<div id="calendar">
  <h1>Four Week View</h1>
<table id="cal">
  <tr>
    <th>Sunday</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Saturday</th>
  </tr>
  <tr>
    <% (@calendar.begin_weekly_calendar..@calendar.end_weekly_calendar(4)).each do |d| %>
      <% if d.wday == 0 %></tr><tr><% end %>
        <td>
          <p class="day"><%= d.day %></p>
          <ol>
            <% Chore.all.each do |e| %>
              <% if e.date_due == d %>
                <li> <%= e.title %></li>
              <% elsif e.schedule == "weekly" && e.date_due.wday == d.wday %>
                <li> <%= e.title %></li>
              <% end %>
            <% end %>
          </ol>
        </td>
      <% end %>
  </tr>
</table>
</div>

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :date_due %><br>
    <%= f.date_field :date_due %>
  </div>
  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.text_field :schedule %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<%if logged_in?%>
  <h1>Editing chore</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @chore %> |
  <%= link_to 'Back', chores_path %>
<% end %>

app/views/chores/index.html.erb
<%if logged_in?%>
  <h1>Listing chores</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Date Due</th>
        <th>Schedule</th>
        <th>Tag</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @chores.each do |chore| %>
        <tr>
          <td><%= chore.title %></td>
          <td><%= chore.body %></td>
          <td><%= chore.date_due %></td>
          <td><%= chore.schedule %></td>
          <td><%= chore.tag %></td>
          <td><%= link_to 'Show', chore %></td>
          <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
          <td><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Chore', new_chore_path %>
<% end %>

app/views/chores/new.html.erb
<%if logged_in?%>
  <h1>New chore</h1>

  <%= render 'form' %>

  <%= link_to 'Back', chores_path %>
<% end %>

app/views/chores/show.html.erb
<%if logged_in?%>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @chore.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @chore.body %>
  </p>

  <p>
    <strong>Date Due:</strong>
    <%= @chore.date_due %>
  </p>

  <p>
    <strong>Schedule:</strong>
    <%= @chore.schedule %>
  </p>

  <p>
    <strong>Tag:</strong>
    <%= @chore.tag %>
  </p>

  <%= link_to 'Edit', edit_chore_path(@chore) %> |
  <%= link_to 'Back', chores_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeeklyMonthly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="content">
      <%= yield %>
      <hr>
      <h6>
        <% if logged_in? %>
          <%= "Logged in as #{current_user.username}" %>
          <%= link_to "(logout)", logout_path %>
        <% else %>
          <%= link_to "(login)", login_path %>
        <% end %>
      </h6>
    </div>
  </div>
</body>
</html>

app/views/user_sessions/new.html.erb
<%if logged_in?%>
  <h1> Welcome Back! </h1>
<% else %>
  <h1>Login</h1>
  <%= form_tag user_sessions_path, method: :post do %>
    <div class="field">
      <%= label_tag :username %>
      <%= text_field_tag :username %>
      <br/>
    </div>
    <div class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <br/>
    </div>
    <div class="actions">
      <%= submit_tag "Login" %>
    </div>
  <% end %>

  <%= link_to 'Back', users_path %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>